---
name: Terraform PR Check
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  terraform:
    name: tf check
    runs-on: dagger
    steps:
      - uses: actions/checkout@v4

      - name: AWS Login
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::444106639146:role/gha-iam-role
          role-session-name: ghaSession
          output-credentials: true

      - name: GITHUB_REF
        run: |
          echo $GITHUB_REF
        env:
          GITHUB_REF: ${{ env.GITHUB_REF }}

      - name: tf plan
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          args: plan
            --aws-access-key=AWS_ACCESS_KEY_ID
            --aws-secret-key=AWS_SECRET_ACCESS_KEY
            --aws-session-token=AWS_SESSION_TOKEN
            --github-ref=$GITHUB_REF
            --github-token=$GITHUB_TOKEN
            --github-repository=$GITHUB_REPOSITORY
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.creds.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.creds.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ steps.creds.outputs.aws-session-token }}
          GITHUB_REF: ${{ env.GITHUB_REF }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
