---
name: Terraform PR Check
on:
  push:
    branches:
      - main
      - develop
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  terraform:
    name: tf check
    runs-on: dagger
    steps:
      - uses: actions/checkout@v4

      - name: AWS Login
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::444106639146:role/gha-iam-role
          role-session-name: ghaSession
          output-credentials: true

      - name: tf plan
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          args: plan --src=. --aws-access-key=env:AWS_ACCESS_KEY_ID --aws-secret-key=env:AWS_SECRET_ACCESS_KEY --aws-session-token=env:AWS_SESSION_TOKEN
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.creds.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.creds.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ steps.creds.outputs.aws-session-token }}
